#!/bin/sh

#
# This is the command we use to run tramonto. 
# change this as needed for your environment
#
TramontoCommand="mpirun -np 2 ../TEST/src/dft"
#TramontoCommand="echo mpirun -np 2 ./xdft_intel_linux"   # use this for debuging the script


# clean up old data
rm -f dft_force.dat

###########################
# 1D Continuation examples
###########################

echo "TEST 1: 1Dcont1 "
# check that needed files are there
if [ -f Ex_surfs/1D_continuation/1Dcont1s -a -f Ex_inputs/1D_continuation/1Dcont1 ]
then
    cp Ex_surfs/1D_continuation/1Dcont1s dft_surfaces.dat
    cp Ex_inputs/1D_continuation/1Dcont1 dft_input.dat 
    ${TramontoCommand}
else
    echo "TEST 1 ERROR -- could not find needed files.  Skipping this test"
fi

echo "TEST s: 1Dcont2 "
# check that needed files are there
if [ -f Ex_surfs/1D_continuation/1Dcont2s -a -f Ex_inputs/1D_continuation/1Dcont2 ]
then
    cp Ex_surfs/1D_continuation/1Dcont2s dft_surfaces.dat
    cp Ex_inputs/1D_continuation/1Dcont2 dft_input.dat
    ${TramontoCommand}
else
    echo "TEST 2 ERROR -- could not find needed files.  Skipping this test"
fi
 
echo "TEST 3: 1Dcont3 "
if [ -f Ex_surfs/1D_continuation/1Dcont3s -a -f Ex_inputs/1D_continuation/1Dcont3 ]
then
    cp Ex_surfs/1D_continuation/1Dcont3s dft_surfaces.dat
    cp Ex_inputs/1D_continuation/1Dcont3 dft_input.dat
    ${TramontoCommand}
else
    echo "TEST 3 ERROR -- could not find needed files.  Skipping this test"
fi


echo "TEST 4: 1Dcont4 "
if [ -f Ex_surfs/1D_continuation/1Dcont4s -a -f Ex_inputs/1D_continuation/1Dcont4 ]
then
    cp Ex_surfs/1D_continuation/1Dcont4s dft_surfaces.dat
    cp Ex_inputs/1D_continuation/1Dcont4 dft_input.dat
    ${TramontoCommand}
else
    echo "TEST 4 ERROR -- could not find needed files.  Skipping this test"
fi

###########################
# 1D Hard Neutral Examples 
###########################

echo "TEST 5: 1Dhn1 "
if [ -f Ex_surfs/1D_hard_neutral/1Dhn1s -a -f Ex_inputs/1D_hard_neutral/1Dhn1 ]
then
    cp Ex_surfs/1D_hard_neutral/1Dhn1s dft_surfaces.dat
    cp Ex_inputs/1D_hard_neutral/1Dhn1 dft_input.dat 
    ${TramontoCommand}
else
    echo "TEST 5 ERROR -- could not find needed files.  Skipping this test"
fi

echo "TEST 6: 1Dhn2"
if [ -f Ex_surfs/1D_hard_neutral/1Dhn2s -a -f Ex_inputs/1D_hard_neutral/1Dhn2 ]
then
    cp Ex_surfs/1D_hard_neutral/1Dhn2s dft_surfaces.dat
    cp Ex_inputs/1D_hard_neutral/1Dhn2 dft_input.dat
    ${TramontoCommand}
else
    echo "TEST 6 ERROR -- could not find needed files.  Skipping this test"
fi

echo "TEST 7: 1Dhn3"
if [ -f Ex_surfs/1D_hard_neutral/1Dhn3s -a -f Ex_inputs/1D_hard_neutral/1Dhn3 ]
then
    cp Ex_surfs/1D_hard_neutral/1Dhn3s dft_surfaces.dat
    cp Ex_inputs/1D_hard_neutral/1Dhn3 dft_input.dat 
    ${TramontoCommand}
else
    echo "TEST 7 ERROR -- could not find needed files.  Skipping this test"
fi

echo "TEST 8: 1Dhn4"
if [ -f Ex_surfs/1D_hard_neutral/1Dhn4s -a -f Ex_inputs/1D_hard_neutral/1Dhn4 ]
then
    cp Ex_surfs/1D_hard_neutral/1Dhn4s dft_surfaces.dat
    cp Ex_inputs/1D_hard_neutral/1Dhn4 dft_input.dat 
    ${TramontoCommand}
else
    echo "TEST 8 ERROR -- could not find needed files.  Skipping this test"
fi

echo "TEST 9: 1Dhn5"
if [ -f Ex_surfs/1D_hard_neutral/1Dhn5s -a -f Ex_inputs/1D_hard_neutral/1Dhn5 ]
then
    cp Ex_surfs/1D_hard_neutral/1Dhn5s dft_surfaces.dat
    cp Ex_inputs/1D_hard_neutral/1Dhn5 dft_input.dat 
    ${TramontoCommand}
else
    echo "TEST 9 ERROR -- could not find needed files.  Skipping this test"
fi

echo "TEST 10: 1Dhn6"
if [ -f Ex_surfs/1D_hard_neutral/1Dhn6s -a -f Ex_inputs/1D_hard_neutral/1Dhn6 ]
then
    cp Ex_surfs/1D_hard_neutral/1Dhn6s dft_surfaces.dat
    cp Ex_inputs/1D_hard_neutral/1Dhn6 dft_input.dat 
    ${TramontoCommand}
else
    echo "TEST 10 ERROR -- could not find needed files.  Skipping this test"
fi

echo "TEST 11: 1Dhn7"
if [ -f Ex_surfs/1D_hard_neutral/1Dhn7s -a -f Ex_inputs/1D_hard_neutral/1Dhn7 ]
then
    cp Ex_surfs/1D_hard_neutral/1Dhn7s dft_surfaces.dat
    cp Ex_inputs/1D_hard_neutral/1Dhn7 dft_input.dat 
    ${TramontoCommand}
else
    echo "TEST 11 ERROR -- could not find needed files.  Skipping this test"
fi

###########################
# 1D LJ Neutral Examples
###########################

echo "TEST 12: 1Dljn1"
if [ -f Ex_surfs/1D_LJ_neutral/1Dljn1s -a -f Ex_inputs/1D_LJ_neutral/1Dljn1 ]
then
    cp Ex_surfs/1D_LJ_neutral/1Dljn1s dft_surfaces.dat
    cp Ex_inputs/1D_LJ_neutral/1Dljn1 dft_input.dat 
    ${TramontoCommand}
else
    echo "TEST 12 ERROR -- could not find needed files.  Skipping this test"
fi

echo "TEST 13: 1Dljn2"
if [ -f Ex_surfs/1D_LJ_neutral/1Dljn2s -a -f Ex_inputs/1D_LJ_neutral/1Dljn2 ]
then
    cp Ex_surfs/1D_LJ_neutral/1Dljn2s dft_surfaces.dat
    cp Ex_inputs/1D_LJ_neutral/1Dljn2 dft_input.dat 
    ${TramontoCommand}
else
    echo "TEST 13 ERROR -- could not find needed files.  Skipping this test"
fi

echo "TEST 14: 1Dljn3"
if [ -f Ex_surfs/1D_LJ_neutral/1Dljn3s -a -f Ex_inputs/1D_LJ_neutral/1Dljn3 ]
then
    cp Ex_surfs/1D_LJ_neutral/1Dljn3s dft_surfaces.dat
    cp Ex_inputs/1D_LJ_neutral/1Dljn3 dft_input.dat
    ${TramontoCommand}
else
    echo "TEST 14 ERROR -- could not find needed files.  Skipping this test"
fi

echo "TEST 15: 1Dljn4"
if [ -f Ex_surfs/1D_LJ_neutral/1Dljn4s -a -f Ex_inputs/1D_LJ_neutral/1Dljn4 ]
then
    cp Ex_surfs/1D_LJ_neutral/1Dljn4s dft_surfaces.dat
    cp Ex_inputs/1D_LJ_neutral/1Dljn4 dft_input.dat
    ${TramontoCommand}
else
    echo "TEST 15 ERROR -- could not find needed files.  Skipping this test"
fi

#########################
# 1D Mixture Examples
#########################

echo "TEST 16: 1Dmix1"
if [ -f Ex_surfs/1D_mixtures/1Dmix1s -a -f Ex_inputs/1D_mixtures/1Dmix1 ]
then
    cp Ex_surfs/1D_mixtures/1Dmix1s dft_surfaces.dat
    cp Ex_inputs/1D_mixtures/1Dmix1 dft_input.dat 
    ${TramontoCommand}
else
    echo "TEST 16 ERROR -- could not find needed files.  Skipping this test"
fi

echo "TEST 17: 1Dmix2"
if [ -f Ex_surfs/1D_mixtures/1Dmix2s -a -f Ex_inputs/1D_mixtures/1Dmix2 ]
then
    cp Ex_surfs/1D_mixtures/1Dmix2s dft_surfaces.dat
    cp Ex_inputs/1D_mixtures/1Dmix2 dft_input.dat
    ${TramontoCommand}
else
    echo "TEST 17 ERROR -- could not find needed files.  Skipping this test"
fi

echo "TEST 18: 1Dmix3"
if [ -f Ex_surfs/1D_mixtures/1Dmix3s -a -f Ex_inputs/1D_mixtures/1Dmix3 ]
then
    cp Ex_surfs/1D_mixtures/1Dmix3s dft_surfaces.dat
    cp Ex_inputs/1D_mixtures/1Dmix3 dft_input.dat
    ${TramontoCommand}
else
    echo "TEST 18 ERROR -- could not find needed files.  Skipping this test"
fi

echo "TEST 19: 1Dmix4"
if [ -f Ex_surfs/1D_mixtures/1Dmix4s -a -f Ex_inputs/1D_mixtures/1Dmix4 ]
then
    cp Ex_surfs/1D_mixtures/1Dmix4s dft_surfaces.dat
    cp Ex_inputs/1D_mixtures/1Dmix4 dft_input.dat
    ${TramontoCommand}
else
    echo "TEST 19 ERROR -- could not find needed files.  Skipping this test"
fi

echo "TEST 20: 1Dmix5"
if [ -f Ex_surfs/1D_mixtures/1Dmix5s -a -f Ex_inputs/1D_mixtures/1Dmix5 ]
then
    cp Ex_surfs/1D_mixtures/1Dmix5s dft_surfaces.dat
    cp Ex_inputs/1D_mixtures/1Dmix5 dft_input.dat
    ${TramontoCommand}
else
    echo "TEST 20 ERROR -- could not find needed files.  Skipping this test"
fi

echo "TEST 21: 1Dmix6"
if [ -f Ex_surfs/1D_mixtures/1Dmix6s -a -f Ex_inputs/1D_mixtures/1Dmix6 ]
then
    cp Ex_surfs/1D_mixtures/1Dmix6s dft_surfaces.dat
    cp Ex_inputs/1D_mixtures/1Dmix6 dft_input.dat
    ${TramontoCommand}
else
    echo "TEST 21 ERROR -- could not find needed files.  Skipping this test"
fi

echo "TEST 22: 1Dmix7"
if [ -f Ex_surfs/1D_mixtures/1Dmix7s -a -f Ex_inputs/1D_mixtures/1Dmix7 ]
then
    cp Ex_surfs/1D_mixtures/1Dmix7s dft_surfaces.dat
    cp Ex_inputs/1D_mixtures/1Dmix7 dft_input.dat
    ${TramontoCommand}
else
    echo "TEST 22 ERROR -- could not find needed files.  Skipping this test"
fi

echo "TEST 23: 1Dmix8"
if [ -f Ex_surfs/1D_mixtures/1Dmix8s -a -f Ex_inputs/1D_mixtures/1Dmix8 ]
then
    cp Ex_surfs/1D_mixtures/1Dmix8s dft_surfaces.dat
    cp Ex_inputs/1D_mixtures/1Dmix8 dft_input.dat
    ${TramontoCommand}
else
    echo "TEST 23 ERROR -- could not find needed files.  Skipping this test"
fi

echo "TEST 24: 1Dmix9"
if [ -f Ex_surfs/1D_mixtures/1Dmix9s -a -f Ex_inputs/1D_mixtures/1Dmix9 ]
then
    cp Ex_surfs/1D_mixtures/1Dmix9s dft_surfaces.dat
    cp Ex_inputs/1D_mixtures/1Dmix9 dft_input.dat
    ${TramontoCommand}
else
    echo "TEST 24 ERROR -- could not find needed files.  Skipping this test"
fi

#########################
# 1D Polymer Examples
#########################

echo "TEST 25: 1Dpoly1"
if [ -f Ex_surfs/1D_polymer/1Dpoly1s -a -f Ex_inputs/1D_polymer/1Dpoly1 -a -f Ex_polyfiles/lin_18 -a -f Ex_crfiles/cr8.2.8_0.711eff1 ]
then
    cp Ex_surfs/1D_polymer/1Dpoly1s dft_surfaces.dat
    cp Ex_inputs/1D_polymer/1Dpoly1 dft_input.dat 
    cp Ex_polyfiles/lin_18 lin_18
    cp Ex_crfiles/cr8.2.8_0.711eff1 cr8.2.8_0.711eff1
    ${TramontoCommand}
else
    echo "TEST 25 ERROR -- could not find needed files.  Skipping this test"
fi

echo "TEST 26: 1Dpoly2"
if [ -f Ex_surfs/1D_polymer/1Dpoly2s -a -f Ex_inputs/1D_polymer/1Dpoly2 -a -f Ex_polyfiles/lin_18 -a -f Ex_crfiles/cr8.2.8_0.711eff1 ]
then
    cp Ex_surfs/1D_polymer/1Dpoly2s dft_surfaces.dat
    cp Ex_inputs/1D_polymer/1Dpoly2 dft_input.dat
    cp Ex_polyfiles/lin_18 lin_18
    cp Ex_crfiles/cr8.2.8_0.711eff1 cr8.2.8_0.711eff1
    ${TramontoCommand}
else
    echo "TEST 26 ERROR -- could not find needed files.  Skipping this test"
fi

echo "TEST 27: 1Dpoly3"
if [ -f Ex_surfs/1D_polymer/1Dpoly3s -a -f Ex_inputs/1D_polymer/1Dpoly3 -a -f Ex_polyfiles/lin_18_1 -a -f Ex_crfiles/cr8.2.8_0.375_1_0.375 ]
then
    cp Ex_surfs/1D_polymer/1Dpoly3s dft_surfaces.dat
    cp Ex_inputs/1D_polymer/1Dpoly3 dft_input.dat
    cp Ex_polyfiles/lin_18_1 lin_18_1
    cp Ex_crfiles/cr8.2.8_0.375_1_0.375 cr8.2.8_0.375_1_0.375
    ${TramontoCommand}
else
    echo "TEST 27 ERROR -- could not find needed files.  Skipping this test"
fi

echo "TEST 28: 1Dpoly4"
if [ -f Ex_surfs/1D_polymer/1Dpoly4s -a -f Ex_inputs/1D_polymer/1Dpoly4 -a -f Ex_polyfiles/lin_18_1 -a -f Ex_crfiles/cr8.2.8_0.375_1_0.375 ]
then
    cp Ex_surfs/1D_polymer/1Dpoly4s dft_surfaces.dat
    cp Ex_inputs/1D_polymer/1Dpoly4 dft_input.dat
    cp Ex_polyfiles/lin_18_1 lin_18_1
    cp Ex_crfiles/cr8.2.8_0.375_1_0.375 cr8.2.8_0.375_1_0.375
    ${TramontoCommand}
    rm lin_18_1
else
    echo "TEST 28 ERROR -- could not find needed files.  Skipping this test"
fi

echo "TEST 29: 1Dpoly5"
if [ -f Ex_surfs/1D_polymer/1Dpoly5s -a -f Ex_inputs/1D_polymer/1Dpoly5 -a -f Ex_polyfiles/lin_3mer -a -f Ex_crfiles/cr8.2.8_0.375_1_0.375 ]
then
    cp Ex_surfs/1D_polymer/1Dpoly5s dft_surfaces.dat
    cp Ex_inputs/1D_polymer/1Dpoly5 dft_input.dat
    cp Ex_polyfiles/lin_3mer lin_3mer
    cp Ex_crfiles/cr8.2.8_0.375_1_0.375 cr8.2.8_0.375_1_0.375
    ${TramontoCommand}
    rm lin_3mer
else
    echo "TEST 29 ERROR -- could not find needed files.  Skipping this test"
fi

echo "TEST 30: 1Dpoly6"
if [ -f Ex_surfs/1D_polymer/1Dpoly6s -a -f Ex_inputs/1D_polymer/1Dpoly6 -a -f Ex_polyfiles/lin_5mer -a -f Ex_crfiles/cr8.2.8_0.375_1_0.375 ]
then
    cp Ex_surfs/1D_polymer/1Dpoly6s dft_surfaces.dat
    cp Ex_inputs/1D_polymer/1Dpoly6 dft_input.dat
    cp Ex_polyfiles/lin_5mer lin_5mer
    cp Ex_crfiles/cr8.2.8_0.375_1_0.375 cr8.2.8_0.375_1_0.375
    ${TramontoCommand}
else
    echo "TEST 30 ERROR -- could not find needed files.  Skipping this test"
fi

echo "TEST 31: 1Dpoly7"
if [ -f Ex_surfs/1D_polymer/1Dpoly7s -a -f Ex_inputs/1D_polymer/1Dpoly7 -a -f Ex_polyfiles/lin_5mer -a -f Ex_crfiles/cr8.2.8_0.375_1_0.375 ]
then
    cp Ex_surfs/1D_polymer/1Dpoly7s dft_surfaces.dat
    cp Ex_inputs/1D_polymer/1Dpoly7 dft_input.dat
    cp Ex_polyfiles/lin_5mer lin_5mer
    cp Ex_crfiles/cr8.2.8_0.375_1_0.375 cr8.2.8_0.375_1_0.375
    ${TramontoCommand}
else
    echo "TEST 31 ERROR -- could not find needed files.  Skipping this test"
fi

echo "TEST 32: 1Dpoly8"
if [ -f Ex_surfs/1D_polymer/1Dpoly8s -a -f Ex_inputs/1D_polymer/1Dpoly8 -a -f Ex_polyfiles/lin_5mer -a -f Ex_crfiles/cr8.2.8_0.375_1_0.375 ]
then
    cp Ex_surfs/1D_polymer/1Dpoly8s dft_surfaces.dat
    cp Ex_inputs/1D_polymer/1Dpoly8 dft_input.dat
    cp Ex_polyfiles/lin_5mer lin_5mer
    cp Ex_crfiles/cr8.2.8_0.375_1_0.375 cr8.2.8_0.375_1_0.375
    ${TramontoCommand}
    rm lin_5mer
    rm cr8.2.8_0.375_1_0.375
else
    echo "TEST 32 ERROR -- could not find needed files.  Skipping this test"
fi

#########################
# 2D3D Atomic Examples
#########################

echo "TEST 33: 2D3Datomic1"
if [ -f Ex_surfs/2D3D_atomic/2D3Datomic1s -a -f Ex_inputs/2D3D_atomic/2D3Datomic1 ]
then
    cp Ex_surfs/2D3D_atomic/2D3Datomic1s dft_surfaces.dat
    cp Ex_inputs/2D3D_atomic/2D3Datomic1 dft_input.dat
    ${TramontoCommand}
else
    echo "TEST 33 ERROR -- could not find needed files.  Skipping this test"
fi

echo "TEST 34: 2D3Datomic2"
if [ -f Ex_surfs/2D3D_atomic/2D3Datomic2s -a -f Ex_inputs/2D3D_atomic/2D3Datomic2 ]
then
    cp Ex_surfs/2D3D_atomic/2D3Datomic2s dft_surfaces.dat
    cp Ex_inputs/2D3D_atomic/2D3Datomic2 dft_input.dat
    ${TramontoCommand}
else
    echo "TEST 34 ERROR -- could not find needed files.  Skipping this test"
fi

echo "TEST 35: 2D3Datomic3"
if [ -f Ex_surfs/2D3D_atomic/2D3Datomic3s -a -f Ex_inputs/2D3D_atomic/2D3Datomic3 ]
then
    cp Ex_surfs/2D3D_atomic/2D3Datomic3s dft_surfaces.dat
    cp Ex_inputs/2D3D_atomic/2D3Datomic3 dft_input.dat
    ${TramontoCommand}
else
    echo "TEST 35 ERROR -- could not find needed files.  Skipping this test"
fi

echo "TEST 36: 2D3Datomic4"
if [ -f Ex_surfs/2D3D_atomic/2D3Datomic4s -a -f Ex_inputs/2D3D_atomic/2D3Datomic4 ]
then
    cp Ex_surfs/2D3D_atomic/2D3Datomic4s dft_surfaces.dat
    cp Ex_inputs/2D3D_atomic/2D3Datomic4 dft_input.dat
    ${TramontoCommand}
else
    echo "TEST 36 ERROR -- could not find needed files.  Skipping this test"
fi


echo "TEST 37: 2D3Datomic5"
if [ -f Ex_surfs/2D3D_atomic/2D3Datomic5s -a -f Ex_inputs/2D3D_atomic/2D3Datomic5 ]
then
    cp Ex_surfs/2D3D_atomic/2D3Datomic5s dft_surfaces.dat
    cp Ex_inputs/2D3D_atomic/2D3Datomic5 dft_input.dat
    ${TramontoCommand}
else
    echo "TEST 37 ERROR -- could not find needed files.  Skipping this test"
fi

echo "TEST 38: 2D3Datomic6"
if [ -f Ex_surfs/2D3D_atomic/2D3Datomic6s -a -f Ex_inputs/2D3D_atomic/2D3Datomic6 ]
then
    cp Ex_surfs/2D3D_atomic/2D3Datomic6s dft_surfaces.dat
    cp Ex_inputs/2D3D_atomic/2D3Datomic6 dft_input.dat
    ${TramontoCommand}
else
    echo "TEST 38 ERROR -- could not find needed files.  Skipping this test"
fi

echo "TEST 39: 2D3Datomic7"
if [ -f Ex_surfs/2D3D_atomic/2D3Datomic7s -a -f Ex_inputs/2D3D_atomic/2D3Datomic7 ]
then
    cp Ex_surfs/2D3D_atomic/2D3Datomic7s dft_surfaces.dat
    cp Ex_inputs/2D3D_atomic/2D3Datomic7 dft_input.dat
    ${TramontoCommand}
else
    echo "TEST 39 ERROR -- could not find needed files.  Skipping this test"
fi

echo "TEST 40: 2D3Datomic8"
if [ -f Ex_surfs/2D3D_atomic/2D3Datomic8s -a -f Ex_inputs/2D3D_atomic/2D3Datomic8 ]
then
    cp Ex_surfs/2D3D_atomic/2D3Datomic8s dft_surfaces.dat
    cp Ex_inputs/2D3D_atomic/2D3Datomic8 dft_input.dat
    ${TramontoCommand}
else
    echo "TEST 40 ERROR -- could not find needed files.  Skipping this test"
fi

echo "TEST 41: 2D3Datomic9"
if [ -f Ex_surfs/2D3D_atomic/2D3Datomic9s -a -f Ex_inputs/2D3D_atomic/2D3Datomic9 ]
then
    cp Ex_surfs/2D3D_atomic/2D3Datomic9s dft_surfaces.dat
    cp Ex_inputs/2D3D_atomic/2D3Datomic9 dft_input.dat
    ${TramontoCommand}
else
    echo "TEST 41 ERROR -- could not find needed files.  Skipping this test"
fi

#turning point tracking (generates 2 lines in dft_force.dat)
echo "TEST 42: 2D3Datomic10"
if [ -f Ex_surfs/2D3D_atomic/2D3Datomic10s -a -f Ex_inputs/2D3D_atomic/2D3Datomic10 ]
then
    cp Ex_surfs/2D3D_atomic/2D3Datomic10s dft_surfaces.dat
    cp Ex_inputs/2D3D_atomic/2D3Datomic10 dft_input.dat
    ${TramontoCommand}
else
    echo "TEST 42 ERROR -- could not find needed files.  Skipping this test"
fi

echo "TEST 43: 2D3Datomic11"
if [ -f Ex_surfs/2D3D_atomic/2D3Datomic11s -a -f Ex_inputs/2D3D_atomic/2D3Datomic11 ]
then
    cp Ex_surfs/2D3D_atomic/2D3Datomic11s dft_surfaces.dat
    cp Ex_inputs/2D3D_atomic/2D3Datomic11 dft_input.dat
    ${TramontoCommand}
else
    echo "TEST 43 ERROR -- could not find needed files.  Skipping this test"
fi

echo "TEST 44: 2D3Datomic12"
if [ -f Ex_surfs/2D3D_atomic/2D3Datomic12s -a -f Ex_inputs/2D3D_atomic/2D3Datomic12 ]
then
    cp Ex_surfs/2D3D_atomic/2D3Datomic12s dft_surfaces.dat
    cp Ex_inputs/2D3D_atomic/2D3Datomic12 dft_input.dat
    ${TramontoCommand}
else
    echo "TEST 44 ERROR -- could not find needed files.  Skipping this test"
fi

############
# clean up #
############
rm -f dft_input.dat
rm -f dft_surfaces.dat
rm -f dft_out.lis
rm -f dft_dens.dat
rm -f dft_dens.dat
rm -f dens36save
rm -f crf* star* lin*
rm -f dft_dens.datg
rm -f proc_mesh.dat
